### ISSUE TITLE
Keycloak failed to connect to Postgresql with parameter KEYCLOAK_JDBC_PARAMS: value: "sslmode=require"

### ISSUE THREAD

**Issue by muzaparoff** [mnasyrov/keycloak-postgres-ssl#1]
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "10.233.82.90", user "keycloak", database "keycloak", SSL off
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:408)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:181)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:144)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc3g.Jdbc3gConnection.<init>(Jdbc3gConnection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:410)
	at org.postgresql.Driver.connect(Driver.java:280)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:321)

**Comment by mnasyrov** [comment]
I think there is nothing to fix: KEYCLOAK_JDBC_PARAMS passes its value to JDBC url's query string as is.
Does your pg_hba.conf configured properly? Did you pass `ssl=true` as well? Can you connect by another client using SSL to the DB?

**Comment by mnasyrov** [comment]
Closed because there is not enough input about the issue.

**Comment by mnasyrov** [comment]
Reopened the issue because it needs to test with the latest Keycloak's image (v3.3.0+): they changed a way how the image and Keycloak are configured.

As workaround, I recommend to use the previous tagged image: `mnasyrov/keycloak-postgres-ssl:3.2.1.Final`

**Comment by muzaparoff** [comment]
Hi @mnasyrov. Thanks for you vry fast answer. I working with K8S helm charts. I build SSL postgres, and connect to him two other apps that worked. I tried to use your image tag `mnasyrov/keycloak-postgres-ssl:3.2.1.Final`, getting error that was described above.
Here example of connection string that I use for other apps:
`jdbc:postgresql://infra-postgres-stolon-proxy:5432/gitlab?sslmode=require`
In the params of `KEYCLOAK_JDBC_PARAMS` I set `'sslmode=require'`
What do you think? Do you tried it with K8S?

**Comment by mnasyrov** [comment]
It might be need to pass `ssl=true` explicitly along with `sslmode`: `ssl=true&sslmode=require`. Hope will have a time soon to test the case.
I'm using the image against Azure's Postgres.

**Comment by mnasyrov** [comment]
I believe that you have an incorrect `pg_hba.conf` configuration, please check https://www.postgresql.org/docs/9.6/static/auth-pg-hba-conf.html

I've just tested `mnasyrov/keycloak-postgres-ssl:3.2.1.Final` with `postgres:9.6` using a self-signed certificate. All options for `KEYCLOAK_JDBC_PARAMS` work successfully: `ssl=true`, `sslmode=require`, `sslmode=verify-ca` and `sslmode=verify-full`.

Startup scripts:
```bash
docker run --rm --name postgres-ssl -d -p 54320:5432 \
  -e POSTGRES_PASSWORD=password \
  -v ${PG_DIR}/server.crt:/srv/server.crt \
  -v ${PG_DIR}/server.key:/srv/server.key \
  -v ${PG_DIR}/postgresql.conf:/srv/postgresql.conf \
  -v ${PG_DIR}/reconfigure_postgres.sh:/docker-entrypoint-initdb.d/reconfigure_postgres.sh \
  -v ${PG_DIR}/init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql \
  postgres:9.6

docker run --rm --name keycloak-test-3.2.1.Final -p 9080:8080 \
  --link postgres-ssl:postgres \
  -e KEYCLOAK_POSTGRES_HOST=postgres \
  -e KEYCLOAK_POSTGRES_DATABASE=keycloak-db \
  -e KEYCLOAK_POSTGRES_USER=keycloak-user \
  -e KEYCLOAK_POSTGRES_PASSWORD=keycloak \
  -e KEYCLOAK_JDBC_PARAMS='sslmode=verify-ca' \
  -v ${KEYCLOAK_DIR}/keycloak-certs.jks:/opt/jboss/keycloak-certs.jks \
  mnasyrov/keycloak-postgres-ssl:3.2.1.Final \
  -b=0.0.0.0 \
  -Djavax.net.ssl.trustStore=/opt/jboss/keycloak-certs.jks \
  -Djavax.net.ssl.trustStorePassword=password
```
