### ISSUE TITLE
Image with tag "latest" and "pgdriver-42.1.1" fails with params of jboss image

### ISSUE THREAD

**Issue by muzaparoff** [mnasyrov/keycloak-postgres-ssl#2]
10:46:28,456 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "KeycloakDS")
]) - failure description: "WFLYCTL0211: Cannot resolve expression 'jdbc:postgresql://${env.POSTGRES_PORT_5432_TCP_ADDR}:${env.POSTGRES_PORT_5432_TCP_PORT:5432}/${env.POSTGRES_DATABASE:keycloak}'"

I think you forgot to put you image params...

**Comment by seboudry** [comment]
Hi, I've also this issue and have to use v42.X of PostgreSQL JDBC drivers (instead of v9.X).

@mnasyrov  Maybe the simplest fix is to make branch `pgdriver-42.1.1` behave the same way as `3.2.1.Final` 
- base image `jboss/keycloak:3.2.1.Final`
- change `KEYCLOAK_POSTGRES_SSL` to `KEYCLOAK_JDBC_PARAMS`

**Comment by mnasyrov** [comment]
`pgdriver-42.1.1` branch will be removed: it was an experimental and Keycloak 3.3.x uses 42.1.4 driver now out of the box.

**Comment by seboudry** [comment]
In fact, in needed it because Keycloak 3.3 is still in RC and driver 42.X have `sslrootcert`JDBC parameter to specify server CA cert. In driver 9.X, the only solution is to put this certificate in trustore.

If you want I can purpose a PR with branch `3.2.1.Final_pgjdbc-42.1.4`.

**Comment by mnasyrov** [comment]
@Secathor Thank you for the idea! I'll make `3.2.1.Final_pgjdbc-42.1.4` branch myself because planning to reorganise the repo.

**Comment by mnasyrov** [comment]
Replaced `pgdriver-42.1.1` branch by a new `3.2.1.Final_pgjdbc-42.1.4` image tag, the docker image was deleted too.
The new tag has the latest postgres driver and common environment variables.

**Comment by seboudry** [comment]
Really appreciate it !
Nice job
