### ISSUE TITLE
jboss/keycloak v3.3+ docker image

### ISSUE THREAD

**Issue by seboudry** [mnasyrov/keycloak-postgres-ssl#3]
Hi,
The master branch of official jboss/postgres repo have a lot of changes around postgres persistence.
The only things left is the support of SSL and define a specified host/port.
Do you know if you'll continue to maintain this repo with next Keycloak 3.3.0 version ?

**Comment by mnasyrov** [comment]
I'm using this image for own apps, so will maintain it while Keycloak will not support JDBC or SSL parameters. I'm just a bit of overwhelmed right now.

**Comment by mnasyrov** [comment]
Introduced `upstream` image tag which follows `jboss/keycloak:latest` images.
JDBC configuration was aligned with the latest changes of Keycloak 3.3.
